language: csharp

git:
  depth: 1

mono: none
dotnet: 2.0.0

matrix:
  include:
    - script:
      - dotnet restore ./homeWork\ 7/T1-GenericList/
      - dotnet build ./homeWork\ 7/T1-GenericList/
    - script:
      - cd ./homeWork\ 7/T1-GenericList//Tests/
      - dotnet test

