language: csharp

git:
  depth: 1

mono: none
dotnet: 2.0.0

matrix:
  include:
    - solution: ./homeWork\ 5/T1-Funcs/T1-Funcs.sln
    - script:
        - cd ./homeWork\ 5/T1-Funcs/Tests/
        - dotnet test

