language: csharp

git:
  depth: 1

mono: none
dotnet: 2.0.0

matrix:
  include:
    - script:
        - ls
        - cd ./homeWork\ 5/T1-Funcs && dotnet restore && dotnet add
    - script:
        - cd ./homeWork\ 5/T1-Funcs/Tests/
        - dotnet test

