
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Entry entry1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button CleanButton;

	private global::Gtk.Button LeftBracketButton;

	private global::Gtk.Button RightBracketButton;

	private global::Gtk.Button BackspaceButton;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button Num7Button;

	private global::Gtk.Button Num8Button;

	private global::Gtk.Button Num9Button;

	private global::Gtk.Button button5;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button Num4Button;

	private global::Gtk.Button Num5Button;

	private global::Gtk.Button Num6Button;

	private global::Gtk.Button button9;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button Num1Button;

	private global::Gtk.Button Num2Button;

	private global::Gtk.Button Num3Button;

	private global::Gtk.Button button11;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button ZeroButton;

	private global::Gtk.Button button15;

	private global::Gtk.Button EvaluateButton;

	private global::Gtk.Button button13;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vbox1.Add(this.entry1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.CleanButton = new global::Gtk.Button();
		this.CleanButton.WidthRequest = 30;
		this.CleanButton.HeightRequest = 30;
		this.CleanButton.CanFocus = true;
		this.CleanButton.Name = "CleanButton";
		this.CleanButton.UseUnderline = true;
		this.CleanButton.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox5.Add(this.CleanButton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.CleanButton]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.LeftBracketButton = new global::Gtk.Button();
		this.LeftBracketButton.WidthRequest = 30;
		this.LeftBracketButton.HeightRequest = 30;
		this.LeftBracketButton.CanFocus = true;
		this.LeftBracketButton.Name = "LeftBracketButton";
		this.LeftBracketButton.UseUnderline = true;
		this.LeftBracketButton.Label = global::Mono.Unix.Catalog.GetString("(");
		this.hbox5.Add(this.LeftBracketButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.LeftBracketButton]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.RightBracketButton = new global::Gtk.Button();
		this.RightBracketButton.WidthRequest = 30;
		this.RightBracketButton.HeightRequest = 30;
		this.RightBracketButton.CanFocus = true;
		this.RightBracketButton.Name = "RightBracketButton";
		this.RightBracketButton.UseUnderline = true;
		this.RightBracketButton.Label = global::Mono.Unix.Catalog.GetString(")");
		this.hbox5.Add(this.RightBracketButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.RightBracketButton]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.BackspaceButton = new global::Gtk.Button();
		this.BackspaceButton.CanFocus = true;
		this.BackspaceButton.Name = "BackspaceButton";
		this.BackspaceButton.UseUnderline = true;
		this.BackspaceButton.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.hbox5.Add(this.BackspaceButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.BackspaceButton]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Num7Button = new global::Gtk.Button();
		this.Num7Button.WidthRequest = 30;
		this.Num7Button.HeightRequest = 30;
		this.Num7Button.CanFocus = true;
		this.Num7Button.Name = "Num7Button";
		this.Num7Button.UseUnderline = true;
		this.Num7Button.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox4.Add(this.Num7Button);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Num7Button]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Num8Button = new global::Gtk.Button();
		this.Num8Button.CanFocus = true;
		this.Num8Button.Name = "Num8Button";
		this.Num8Button.UseUnderline = true;
		this.Num8Button.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox4.Add(this.Num8Button);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Num8Button]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Num9Button = new global::Gtk.Button();
		this.Num9Button.CanFocus = true;
		this.Num9Button.Name = "Num9Button";
		this.Num9Button.UseUnderline = true;
		this.Num9Button.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox4.Add(this.Num9Button);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Num9Button]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.hbox4.Add(this.button5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button5]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Num4Button = new global::Gtk.Button();
		this.Num4Button.CanFocus = true;
		this.Num4Button.Name = "Num4Button";
		this.Num4Button.UseUnderline = true;
		this.Num4Button.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox3.Add(this.Num4Button);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Num4Button]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Num5Button = new global::Gtk.Button();
		this.Num5Button.CanFocus = true;
		this.Num5Button.Name = "Num5Button";
		this.Num5Button.UseUnderline = true;
		this.Num5Button.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox3.Add(this.Num5Button);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Num5Button]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Num6Button = new global::Gtk.Button();
		this.Num6Button.CanFocus = true;
		this.Num6Button.Name = "Num6Button";
		this.Num6Button.UseUnderline = true;
		this.Num6Button.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox3.Add(this.Num6Button);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Num6Button]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.hbox3.Add(this.button9);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button9]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Num1Button = new global::Gtk.Button();
		this.Num1Button.CanFocus = true;
		this.Num1Button.Name = "Num1Button";
		this.Num1Button.UseUnderline = true;
		this.Num1Button.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox2.Add(this.Num1Button);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.Num1Button]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Num2Button = new global::Gtk.Button();
		this.Num2Button.CanFocus = true;
		this.Num2Button.Name = "Num2Button";
		this.Num2Button.UseUnderline = true;
		this.Num2Button.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox2.Add(this.Num2Button);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.Num2Button]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Num3Button = new global::Gtk.Button();
		this.Num3Button.CanFocus = true;
		this.Num3Button.Name = "Num3Button";
		this.Num3Button.UseUnderline = true;
		this.Num3Button.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox2.Add(this.Num3Button);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.Num3Button]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.hbox2.Add(this.button11);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button11]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w21.Position = 4;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.ZeroButton = new global::Gtk.Button();
		this.ZeroButton.CanFocus = true;
		this.ZeroButton.Name = "ZeroButton";
		this.ZeroButton.UseUnderline = true;
		this.ZeroButton.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox1.Add(this.ZeroButton);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ZeroButton]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox1.Add(this.button15);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button15]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.EvaluateButton = new global::Gtk.Button();
		this.EvaluateButton.CanFocus = true;
		this.EvaluateButton.Name = "EvaluateButton";
		this.EvaluateButton.UseUnderline = true;
		this.EvaluateButton.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox1.Add(this.EvaluateButton);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.EvaluateButton]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.hbox1.Add(this.button13);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button13]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w26.Position = 5;
		w26.Expand = false;
		w26.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 174;
		this.DefaultHeight = 207;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
